CREATE TABLE `pessoas` (
	`codigo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(50) NOT NULL DEFAULT '0',
	`telefone` VARCHAR(50) NOT NULL DEFAULT '',
	`estado` VARCHAR(50) NOT NULL DEFAULT '',
	`cidade` VARCHAR(50) NOT NULL DEFAULT '',
	`bairro` VARCHAR(50) NOT NULL DEFAULT '',
	`email` VARCHAR(50) NOT NULL DEFAULT '',
	`senha` VARCHAR(50) NOT NULL DEFAULT '',
	`ativo` TINYINT(1) NOT NULL DEFAULT '1',
	PRIMARY KEY (`codigo`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=9
;
